version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  flask:
    build:
      context: ./flask
      dockerfile: dockerfile
    container_name: flask
    hostname: flask
    ports:
      - "5002:5002"
    depends_on:
      - kafka
  line:
    build:
      context: ./line
      dockerfile: dockerfile
    container_name: line
    hostname: line
    ports:
      - "5000:5000"
    depends_on:
      - kafka

  ngrok:
    image: wernight/ngrok
    container_name: chatbot_ngrok
    tty: true
    stdin_open: true
    ports:
      - "54089:4040"
    depends_on:
      - line
    command: ngrok http line:5000

  ngrok1:
    image: wernight/ngrok
    container_name: flask_ngrok
    tty: true
    stdin_open: true
    ports:
      - "54088:4040"
    depends_on:
      - line
    command: ngrok http flask:5002
